# ============================================
# 秒杀系统 K8s 一键部署配置
# 使用方法: kubectl apply -f all-in-one.yaml
# ============================================

# --- 命名空间 ---
apiVersion: v1
kind: Namespace
metadata:
  name: seckill
---
# --- 配置 ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seckill-config
  namespace: seckill
data:
  PORT: "3000"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: seckill-secret
  namespace: seckill
stringData:
  DATABASE_URL: "mysql://root:123456@mysql-svc:3306/flash_sale"
  RABBITMQ_URL: "amqp://admin:123456@rabbitmq-svc:5672"
---
# --- MySQL ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: seckill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: "flash_sale"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: seckill
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
# --- Redis ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: seckill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: seckill
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
# --- RabbitMQ ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: seckill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: seckill
spec:
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: management
  selector:
    app: rabbitmq
---
# --- 秒杀 API ---
# ⚠️ 修改下面的 image 为你的镜像地址！
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seckill-api
  namespace: seckill
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seckill-api
  template:
    metadata:
      labels:
        app: seckill-api
    spec:
      containers:
        - name: api
          image: your-registry/seckill-api:latest  # ⚠️ 改这里！
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: seckill-config
            - secretRef:
                name: seckill-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: seckill-api-svc
  namespace: seckill
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  selector:
    app: seckill-api
